# Site settings
title: Sahil Jaganmohan
description: My Projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bullpointe.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sahil Jaganmohan
user_description: A senior at Rutgers Preparatory High School involved and interested in research projects in science and technology. Interests are primarily focused on computer applications that aid in scientific research. Genuinely enjoys and plays soccer throughout the year. Actively develops software, varying from genome reconstruction to simple implementations of algorithms.
email: dev.sahil.jaganmohan@gmail.com
twitter_username: sahilJaganmohan
github_username:  bullpointe
gplus_username:  lorem_ipsum
instagram_username: sahilj611
facebook_username: sahil.jaganmohan

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
